### ISSUE TITLE
Chapter 3 - Offline Todo

### ISSUE THREAD

**Issue by matthew-andrews** [matthew-andrews/workshop-making-it-work-offline#2]
- [x] Scaffolding the application
- [x] Opening an IndexedDB database
- [x] Using Dev Tools with Safari, Chrome, IE and Firefox
- [x] Creating Object Stores
- [x] Adding data
- [x] Updating data
- [x] Getting data
- [x] Rendering todos
- [x] Deleting data
- [x] AppCache for full offline experience
